# Generated by Django 5.2 on 2025-05-15 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_scraper', '0002_stockohlc_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('date', models.DateField()),
                ('previous_close', models.FloatField(null=True)),
                ('volatility', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.FloatField()),
                ('buy_date', models.DateField()),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('total_pl', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='stock_scraper.stock')),
            ],
            options={
                'ordering': ['-buy_date'],
            },
        ),
    ]
