# Generated by Django 5.2 on 2025-05-16 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_scraper', '0003_stock_investment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='stock_scraper.stockohlc'),
        ),
        migrations.AlterModelOptions(
            name='stockohlc',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='investment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='stockohlc',
            unique_together={('symbol', 'date')},
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
